
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DO EQUALS IDENTIFIER LET NEWLINE NUMBER RANGE SHOW TOprogram : statement_liststatement_list : statement_list statement\n                      | statementstatement : LET IDENTIFIER EQUALS NUMBER NEWLINEstatement : SHOW IDENTIFIER NEWLINEstatement : RANGE NUMBER TO NUMBER DO NEWLINE statement_list'
    
_lr_action_items = {'LET':([0,2,3,7,12,16,18,19,],[4,4,-3,-2,-5,-4,4,4,]),'SHOW':([0,2,3,7,12,16,18,19,],[5,5,-3,-2,-5,-4,5,5,]),'RANGE':([0,2,3,7,12,16,18,19,],[6,6,-3,-2,-5,-4,6,6,]),'$end':([1,2,3,7,12,16,19,],[0,-1,-3,-2,-5,-4,-6,]),'IDENTIFIER':([4,5,],[8,9,]),'NUMBER':([6,11,13,],[10,14,15,]),'EQUALS':([8,],[11,]),'NEWLINE':([9,14,17,],[12,16,18,]),'TO':([10,],[13,]),'DO':([15,],[17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement_list':([0,18,],[2,19,]),'statement':([0,2,18,19,],[3,7,3,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement_list','program',1,'p_program','flowlang_parser.py',9),
  ('statement_list -> statement_list statement','statement_list',2,'p_statement_list','flowlang_parser.py',13),
  ('statement_list -> statement','statement_list',1,'p_statement_list','flowlang_parser.py',14),
  ('statement -> LET IDENTIFIER EQUALS NUMBER NEWLINE','statement',5,'p_statement_let','flowlang_parser.py',21),
  ('statement -> SHOW IDENTIFIER NEWLINE','statement',3,'p_statement_show','flowlang_parser.py',25),
  ('statement -> RANGE NUMBER TO NUMBER DO NEWLINE statement_list','statement',7,'p_statement_range','flowlang_parser.py',29),
]
